"""Server module — FastAPI application, models, routes, services, and assembly contract."""

from __future__ import annotations

from akgentic.infra.server.app import (
    configure_process,
    create_app,
    create_server_app,
    server_modules,
)
from akgentic.infra.server.assembly import (
    APPLICATION,
    IDENTITY,
    OBSERVABILITY,
    POLICY,
    PROXY,
    SESSION,
    TRANSPORT,
    AllowlistSpec,
    AppManifest,
    AppModule,
    AssemblyError,
    BaseAppModule,
    BuildContext,
    DuplicateModuleNameError,
    DuplicateStateProviderError,
    ExceptionHandlerRegistrar,
    ExceptionHandlerSpec,
    ManifestDelta,
    MiddlewareSpec,
    MissingStateProviderError,
    RouteCollisionError,
    RouteSpec,
    StateEntry,
    UnpopulatedStateError,
    build_app,
    build_manifest,
    manifest_delta,
)
from akgentic.infra.server.deps import CommunityServices, TierServices
from akgentic.infra.server.models import (
    CreateTeamRequest,
    EventListResponse,
    EventResponse,
    HumanInputRequest,
    SendMessageRequest,
    TeamListResponse,
    TeamResponse,
)
from akgentic.infra.server.services.team_service import TeamService
from akgentic.infra.server.settings import CommunitySettings, ServerSettings

__all__ = [
    "APPLICATION",
    "IDENTITY",
    "OBSERVABILITY",
    "POLICY",
    "PROXY",
    "SESSION",
    "TRANSPORT",
    "AllowlistSpec",
    "AppManifest",
    "AppModule",
    "AssemblyError",
    "BaseAppModule",
    "BuildContext",
    "CommunitySettings",
    "CommunityServices",
    "CreateTeamRequest",
    "DuplicateModuleNameError",
    "DuplicateStateProviderError",
    "EventListResponse",
    "EventResponse",
    "ExceptionHandlerRegistrar",
    "ExceptionHandlerSpec",
    "HumanInputRequest",
    "ManifestDelta",
    "MiddlewareSpec",
    "MissingStateProviderError",
    "RouteCollisionError",
    "RouteSpec",
    "SendMessageRequest",
    "ServerSettings",
    "StateEntry",
    "TeamListResponse",
    "TeamResponse",
    "TeamService",
    "TierServices",
    "UnpopulatedStateError",
    "build_app",
    "build_manifest",
    "configure_process",
    "create_app",
    "create_server_app",
    "manifest_delta",
    "server_modules",
]
